# server:
#   port: 8080
#   servlet:
#     context-path: /api

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/ma_base
#     username: utilisateur
#     password: motdepasse
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   profiles:
#     active: dev

# logging:
#   level:
#     root: INFO
#     com.example: DEBUG
#   file:
#     name: logs/app.log

# myapp:
#   url: https://example.com
#   admin:
#     email: admin@example.com

# springdoc:
#   api-docs:
#     path: /v3/api-docs
#   swagger-ui:
#     path: /swagger-ui.html
